// ======================================================================
// \title  CoreComponentTesterHelpers.cpp
// \author Generated by fpp-to-cpp
// \brief  cpp file for CoreComponent component test harness helper functions
// ======================================================================

#include "CoreComponentTester.hpp"

namespace Components {

  // ----------------------------------------------------------------------
  // Helper functions
  // ----------------------------------------------------------------------

  void CoreComponentTester ::
    connectPorts()
  {
    // Connect special input ports

    this->connect_to_cmdIn(
      0,
      this->component.get_cmdIn_InputPort(0)
    );

    // Connect special output ports

    this->component.set_cmdRegOut_OutputPort(
      0,
      this->get_from_cmdRegOut(0)
    );

    this->component.set_cmdResponseOut_OutputPort(
      0,
      this->get_from_cmdResponseOut(0)
    );

    this->component.set_timeCaller_OutputPort(
      0,
      this->get_from_timeCaller(0)
    );
  }

  void CoreComponentTester ::
    initComponents()
  {
    this->init();
    this->component.init(CoreComponentTester::TEST_INSTANCE_QUEUE_DEPTH, CoreComponentTester::TEST_INSTANCE_ID);
  }

}
